# Generated by Django 5.0.8 on 2024-10-23 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0007_product_product_link_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_value",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(1000000000)],
            ),
        ),
    ]
