# Generated by Django 5.0.8 on 2024-10-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccounts", "0017_remove_userearnings_old_earnings_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="individualprofile",
            name="position",
            field=models.CharField(
                choices=[("left", "LEFT"), ("right", "Right")],
                default="left",
                max_length=20,
            ),
        ),
    ]
