# Generated by Django 5.0.8 on 2024-10-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useraccounts", "0018_individualprofile_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="individualprofile",
            name="account_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="individualprofile",
            name="account_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="individualprofile",
            name="bank_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="individualprofile",
            name="payment_method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
